Cite: @Gutwin2010GoneBut, @Rekimoto1997PickDrop
Cotutor: Juan Enrique Garrido Navarro
Csl: input/resources/csl/acm-sig-proceedings.csl
Department: Tecnologías y Sistemas de Información
Language: spanish
Month: Junio
Name: Sergio García Muñoz
Technology: Web
Title: Implementación de Aplicación Web y Desarrollo de Técnicas de Visualización para la Gestión y el Diagnóstico de Patologías 
Tutor: Félix Albertos Marco
Year: 2024
